---
  - name: OBSOLETE MONGOCLIENT | install deps
    apt: name={{item}} state=present
    with_items:
      - php-pear
      - php5-dev
      - libcurl3-openssl-dev
    tags: php-mongo

  - name: OBSOLETE MONGOCLIENT | Detect module path
    shell: echo `php -i | grep extension_dir | awk '{print $(NF)}'`
    register: php_module_path
    tags: php-mongo

  - name: OBSOLETE MONGOCLIENT | Detect ini path
    shell: echo `php -i | grep "Scan this dir for additional .ini files" | awk '{print $(NF)}'`
    register: php_extension_conf_path
    tags: php-mongo


  - name: OBSOLETE MONGOCLIENT |Copy  INI into php.d folder.
    template:
      src: "{{role_dir}}/templates/php-mongo/mongo.ini.j2"
      dest: "{{ php_extension_conf_path.stdout.replace('/cli/','/apache2/') }}/mongo.ini"
      owner: root
      group: root
      mode: 0644
    with_items:
      - {
        php_module_path: "{{php_module_path.stdout}}"
      }
    become: yes
    when: apache_mode == "prefork"
    notify: restart apache2
    tags: php-mongo

  - name: OBSOLETE MONGOCLIENT | Copy  INI into php.d folder.
    template:
      src: "{{role_dir}}/templates/php-mongo/mongo.ini.j2"
      dest: "{{ php_extension_conf_path.stdout.replace('/cli/','/fpm/') }}/mongo.ini"
      owner: root
      group: root
      mode: 0644
    with_items:
      - {
        php_module_path: "{{php_module_path.stdout}}"
      }
    become: yes
    when: apache_mode == "worker"
    notify: restart fpm
    tags: php-mongo

  - name: OBSOLETE MONGOCLIENT | install MongoClient for php
    shell: printf "\n" | pecl install mongo creates={{php_extension_dir.stdout_lines[0]}}/mongo.so
    tags: php-mongo

  - name: OBSOLETE MONGOCLIENT | make mongo.so executable
    file: path={{php_extension_dir.stdout_lines[0]}}/mongo.so mode=0755
    tags: php-mongo
    notify: restart apache2
